"""
AI/ML Expert Skill Pack — domain expertise for Artificial Intelligence and Machine Learning.
"""

from __future__ import annotations

import logging

from backend.modules.coding_agent.skills._types import (
    SkillCapability,
    SkillMetadata,
    SkillResult,
)
from backend.modules.coding_agent.skills.context._models import SkillContext
from backend.modules.coding_agent.skills.packs._base import BaseSkillPack

_LOG = logging.getLogger("naira.coding_agent.skills.packs.ai_ml")


class AIMLExpertPack(BaseSkillPack):
    def __init__(self, *, logger: logging.Logger | None = None) -> None:
        super().__init__(
            logger=logger,
            metadata=SkillMetadata(
                name="AI/ML Expert",
                description="Domain expert for AI/ML — deep learning, LLMs, transformers, scikit-learn, PyTorch, TensorFlow, MLOps",
                supported_languages=("python",),
                supported_frameworks=("pytorch", "tensorflow", "sklearn", "transformers", "langchain", "llama-index"),
                supported_file_extensions=(".py", ".ipynb", ".pth", ".pt", ".h5", ".onnx"),
                priority=50,
            ),
        )

    def _default_capabilities(self) -> list[SkillCapability]:
        return [
            SkillCapability("deep_learning", "Neural networks, CNNs, RNNs, transformers, attention mechanisms", 1.0),
            SkillCapability("llm", "LLM fine-tuning, RAG, prompt engineering, quantization, deployment", 1.0),
            SkillCapability("ml_pipeline", "Data preprocessing, feature engineering, model training, evaluation", 1.0),
            SkillCapability("mlops", "Model registry, experiment tracking, CI/CD for ML, monitoring, A/B testing", 1.0),
            SkillCapability("frameworks", "PyTorch, TensorFlow, scikit-learn, Hugging Face Transformers, LangChain", 1.0),
        ]

    async def _execute_analyse(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(suggestions=["Review model architecture", "Check data preprocessing pipeline", "Verify training/validation split"])

    async def _execute_plan(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# AI/ML Execution Plan\n\n1. Define problem and metrics\n2. Collect and preprocess data\n3. Design model architecture\n4. Implement training loop\n5. Evaluate with appropriate metrics\n6. Optimize hyperparameters\n7. Deploy model (ONNX/TensorRT)\n8. Set up monitoring for drift\n9. Implement MLOps pipeline")

    async def _execute_review(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# AI/ML Code Review\n\n## Data Pipeline\n- Reproducible data splits\n- Proper normalization/scaling\n- Data leakage prevented\n- Class imbalance handled\n## Model\n- Architecture matches problem\n- Proper loss function\n- Regularization applied\n- Learning rate schedule\n## Training\n- Gradient clipping\n- Early stopping\n- Checkpointing\n- TensorBoard/W&B logging\n## MLOps\n- Experiment tracking (MLflow)\n- Model versioning\n- Containerized deployment\n- Drift monitoring")

    async def _execute_generate(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Generated by AI/ML Expert\nimport torch\nimport torch.nn as nn\n\nclass TransformerClassifier(nn.Module):\n    def __init__(self, vocab_size: int, d_model: int = 256, nhead: int = 8, num_classes: int = 2):\n        super().__init__()\n        self.embedding = nn.Embedding(vocab_size, d_model)\n        encoder_layer = nn.TransformerEncoderLayer(d_model, nhead, batch_first=True)\n        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=6)\n        self.classifier = nn.Linear(d_model, num_classes)\n\n    def forward(self, x: torch.Tensor) -> torch.Tensor:\n        x = self.embedding(x)\n        x = self.transformer(x)\n        x = x.mean(dim=1)\n        return self.classifier(x)")

    async def _execute_refactor(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# AI/ML Refactoring\n\n1. Modularize training pipeline\n2. Add configuration (Hydra)\n3. Implement experiment tracking\n4. Optimize data loading (DataLoader)\n5. Add model checkpointing\n6. Implement distributed training")

    async def _execute_debug(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# AI/ML Debug Analysis\n\n## Common Issues\n- Overfitting/underfitting\n- Vanishing/exploding gradients\n- Data leakage\n- NaN losses\n- CUDA out of memory\n## Tools\n- TensorBoard\n- Weights & Biases\n- torchinfo\n- torch.utils.bottleneck\n- Netron (model visualization)")

    async def _execute_explain(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# AI/ML Explanation\n\nAI/ML encompasses algorithms that learn from data, including deep learning, natural language processing, computer vision, and reinforcement learning, with MLOps ensuring production reliability.")


class AIMLExpert:
    AIML = AIMLExpertPack
