"""
C Expert Skill Pack — domain expertise for C programming language.
"""

from __future__ import annotations

import logging

from backend.modules.coding_agent.skills._types import (
    SkillCapability,
    SkillMetadata,
    SkillResult,
)
from backend.modules.coding_agent.skills.context._models import SkillContext
from backend.modules.coding_agent.skills.packs._base import BaseSkillPack

_LOG = logging.getLogger("naira.coding_agent.skills.packs.c")


class CExpertPack(BaseSkillPack):
    def __init__(self, *, logger: logging.Logger | None = None) -> None:
        super().__init__(
            logger=logger,
            metadata=SkillMetadata(
                name="C Expert",
                description="Domain expert for C programming language — memory management, pointers, system programming, and embedded systems",
                supported_languages=("c",),
                supported_frameworks=(),
                supported_file_extensions=(".c", ".h"),
                priority=80,
            ),
        )

    def _default_capabilities(self) -> list[SkillCapability]:
        return [
            SkillCapability("c_syntax", "C syntax and standards (C89, C99, C11, C17, C23)", 1.0),
            SkillCapability("memory_management", "Manual memory management with malloc/free", 1.0),
            SkillCapability("pointers", "Pointer arithmetic, function pointers, void pointers", 1.0),
            SkillCapability("system_programming", "System-level programming, POSIX APIs", 1.0),
            SkillCapability("embedded_c", "Embedded C, microcontrollers, bare-metal programming", 0.9),
            SkillCapability("make_cmake", "Build systems: Make, CMake, Autotools", 0.9),
        ]

    async def _execute_analyse(self, context: SkillContext) -> SkillResult:
        content = f"C Expert analysed {context.current_file.path if context.current_file else 'project'}"
        return SkillResult.ok(content=content, suggestions=["Check memory management", "Verify pointer safety"])

    async def _execute_plan(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# C Execution Plan\n\n1. Analyse requirements\n2. Design data structures\n3. Implement core logic\n4. Add error handling\n5. Memory management review\n6. Compile with -Wall -Wextra -Wpedantic")

    async def _execute_review(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# C Code Review\n\n## Memory Safety\n- Check for NULL pointer dereferences\n- Verify malloc returns checked\n- No buffer overflows\n## Standards\n- C11 or later preferred\n- MISRA-C for embedded\n## Performance\n- Inline small functions\n- Use restrict keyword where applicable")

    async def _execute_generate(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="/* Generated by C Expert */\n#include <stdio.h>\n#include <stdlib.h>\n\nint main(void) {\n    printf(\"Hello from C Expert\\n\");\n    return EXIT_SUCCESS;\n}")

    async def _execute_refactor(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# C Refactoring Suggestions\n\n1. Split large functions\n2. Add const correctness\n3. Use static for internal linkage\n4. Replace magic numbers with defines\n5. Add assertions for invariants")

    async def _execute_debug(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# C Debug Analysis\n\n## Common Issues\n- Buffer overflow\n- Use-after-free\n- Double free\n- Memory leak\n- Uninitialized variables\n## Tools\n- Valgrind\n- AddressSanitizer\n- GDB")

    async def _execute_explain(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# C Explanation\n\nC is a general-purpose systems programming language. Key concepts include pointers, manual memory management, and direct hardware access.")


class CExpert:
    C = CExpertPack
