"""
Competitive Programming Expert Skill Pack — domain expertise for competitive programming.
"""

from __future__ import annotations

import logging

from backend.modules.coding_agent.skills._types import (
    SkillCapability,
    SkillMetadata,
    SkillResult,
)
from backend.modules.coding_agent.skills.context._models import SkillContext
from backend.modules.coding_agent.skills.packs._base import BaseSkillPack

_LOG = logging.getLogger("naira.coding_agent.skills.packs.cp")


class CompetitiveProgrammingExpertPack(BaseSkillPack):
    def __init__(self, *, logger: logging.Logger | None = None) -> None:
        super().__init__(
            logger=logger,
            metadata=SkillMetadata(
                name="Competitive Programming Expert",
                description="Domain expert for competitive programming — CP techniques, library code, problem patterns (LeetCode, Codeforces, AtCoder)",
                supported_languages=("python", "cpp", "java"),
                supported_frameworks=(),
                supported_file_extensions=(),
                priority=40,
            ),
        )

    def _default_capabilities(self) -> list[SkillCapability]:
        return [
            SkillCapability("cp_techniques", "Fast I/O, modular arithmetic, combinatorics, number theory", 1.0),
            SkillCapability("library_code", "Segment tree, Fenwick tree, union-find, suffix array, FFT", 1.0),
            SkillCapability("problem_patterns", "Binary search on answer, meet-in-the-middle, sweep line, Mo's algorithm", 1.0),
            SkillCapability("optimization_cp", "Loop unrolling, memory layout, pragma optimization, template metaprogramming", 1.0),
            SkillCapability("platforms", "Codeforces, LeetCode, AtCoder, ICPC, IOI strategies", 0.9),
        ]

    async def _execute_analyse(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(suggestions=["Analyse constraints for optimal algorithm", "Consider edge cases (n=0, n=1, max values)", "Choose appropriate algorithm pattern"])

    async def _execute_plan(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# CP Execution Plan\n\n1. Read constraints (N, T, memory)\n2. Identify problem type (DP, Graph, Math, String)\n3. Choose algorithm with appropriate complexity\n4. Implement with fast I/O\n5. Test on sample cases\n6. Consider edge cases\n7. Optimize if needed")

    async def _execute_review(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# CP Code Review\n\n## Correctness\n- All constraints handled\n- Integer overflow checked\n- Memory within limits\n- Recursion depth safe\n## Speed\n- Fast I/O (sys.stdin.buffer)\n- Pre-allocated arrays\n- Avoid Python overhead\n- Use PyPy for Python\n## Edge Cases\n- n = 0 or 1\n- Maximum values\n- Negative numbers\n- Duplicate elements\n- Sorted/unsorted input")

    async def _execute_generate(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Generated by CP Expert\nimport sys\n\ninput = sys.stdin.readline\n\ndef solve() -> None:\n    n = int(input())\n    arr = list(map(int, input().split()))\n    \n    # Two-pointer example\n    left, right = 0, n - 1\n    while left < right:\n        print(arr[left], arr[right], end=' ')\n        left += 1\n        right -= 1\n    if left == right:\n        print(arr[left])\n    else:\n        print()\n\nif __name__ == '__main__':\n    solve()")

    async def _execute_refactor(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# CP Refactoring\n\n1. Optimize nested loops\n2. Add fast I/O\n3. Pre-allocate arrays\n4. Use iterative over recursive\n5. Inline function calls")

    async def _execute_debug(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# CP Debug Analysis\n\n## Common Issues\n- TLE (time limit exceeded)\n- MLE (memory limit exceeded)\n- WA (wrong answer)\n- RE (runtime error)\n## Strategies\n- Stress testing with random inputs\n- Test boundary conditions\n- Compare with brute force for small n")

    async def _execute_explain(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# CP Explanation\n\nCompetitive Programming is a mind sport where participants solve algorithmic problems under time and memory constraints, competing on platforms like Codeforces and LeetCode.")


class CompetitiveProgrammingExpert:
    CP = CompetitiveProgrammingExpertPack
