"""
C++ Expert Skill Pack — domain expertise for C++ programming language.
"""

from __future__ import annotations

import logging

from backend.modules.coding_agent.skills._types import (
    SkillCapability,
    SkillMetadata,
    SkillResult,
)
from backend.modules.coding_agent.skills.context._models import SkillContext
from backend.modules.coding_agent.skills.packs._base import BaseSkillPack

_LOG = logging.getLogger("naira.coding_agent.skills.packs.cpp")


class CppExpertPack(BaseSkillPack):
    def __init__(self, *, logger: logging.Logger | None = None) -> None:
        super().__init__(
            logger=logger,
            metadata=SkillMetadata(
                name="C++ Expert",
                description="Domain expert for C++ — OOP, templates, STL, modern C++ (11/14/17/20/23)",
                supported_languages=("cpp", "c++"),
                supported_frameworks=(),
                supported_file_extensions=(".cpp", ".hpp", ".cc", ".cxx", ".hh", ".h++", ".c++"),
                priority=80,
            ),
        )

    def _default_capabilities(self) -> list[SkillCapability]:
        return [
            SkillCapability("modern_cpp", "C++11/14/17/20/23 features", 1.0),
            SkillCapability("stl", "Standard Template Library (containers, algorithms, iterators)", 1.0),
            SkillCapability("templates", "Template metaprogramming, SFINAE, concepts", 1.0),
            SkillCapability("oop", "Object-oriented design, RAII, polymorphism", 1.0),
            SkillCapability("concurrency", "std::thread, std::async, std::future, std::jthread", 0.9),
            SkillCapability("cmake", "CMake build system expertise", 0.9),
        ]

    async def _execute_analyse(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(suggestions=["Check RAII compliance", "Verify const correctness", "Review template usage"])

    async def _execute_plan(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# C++ Execution Plan\n\n1. Design class hierarchy\n2. Implement RAII wrappers\n3. Use STL containers\n4. Add move semantics\n5. Constexpr where possible\n6. Concepts for constraints (C++20)\n7. Unit tests with Google Test")

    async def _execute_review(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# C++ Code Review\n\n## Modern C++ Practices\n- Use auto for type deduction\n- Prefer unique_ptr over raw pointers\n- Use constexpr where applicable\n- noexcept for non-throwing functions\n## Performance\n- Reserve vector capacity\n- Move semantics where beneficial\n- Virtual destructor for base classes\n## Style\n- Follow C++ Core Guidelines\n- Use clang-format")

    async def _execute_generate(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="// Generated by C++ Expert\n#include <iostream>\n#include <memory>\n#include <vector>\n\nauto main() -> int {\n    auto items = std::vector<int>{1, 2, 3};\n    for (const auto& item : items) {\n        std::cout << item << '\\n';\n    }\n    return 0;\n}")

    async def _execute_refactor(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# C++ Refactoring\n\n1. Replace raw pointers with smart pointers\n2. Add move constructors\n3. Use range-based for loops\n4. Replace macros with constexpr\n5. Extract interfaces\n6. Use enum class instead of enum")

    async def _execute_debug(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# C++ Debug Analysis\n\n## Common Issues\n- Undefined behavior\n- Memory corruption\n- Template compilation errors\n- ODR violations\n- Iterator invalidation\n## Tools\n- GDB/LLDB\n- AddressSanitizer\n- UndefinedBehaviorSanitizer\n- Valgrind")

    async def _execute_explain(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# C++ Explanation\n\nC++ is a multi-paradigm language supporting OOP, generic, and functional programming. Modern C++ (C++11 onward) emphasizes RAII, move semantics, and type safety.")


class CppExpert:
    Cpp = CppExpertPack
