"""
DevOps Expert Skill Pack — domain expertise for DevOps practices and tools.
"""

from __future__ import annotations

import logging

from backend.modules.coding_agent.skills._types import (
    SkillCapability,
    SkillMetadata,
    SkillResult,
)
from backend.modules.coding_agent.skills.context._models import SkillContext
from backend.modules.coding_agent.skills.packs._base import BaseSkillPack

_LOG = logging.getLogger("naira.coding_agent.skills.packs.devops")


class DevOpsExpertPack(BaseSkillPack):
    def __init__(self, *, logger: logging.Logger | None = None) -> None:
        super().__init__(
            logger=logger,
            metadata=SkillMetadata(
                name="DevOps Expert",
                description="Domain expert for DevOps — CI/CD, IaC, monitoring, Terraform, Ansible, GitHub Actions",
                supported_languages=(),
                supported_frameworks=(),
                supported_file_extensions=(".tf", ".tfvars", ".yml", ".yaml", ".hcl", ".groovy", ".jenkinsfile"),
                priority=60,
            ),
        )

    def _default_capabilities(self) -> list[SkillCapability]:
        return [
            SkillCapability("cicd", "GitHub Actions, GitLab CI, Jenkins, CircleCI, ArgoCD", 1.0),
            SkillCapability("iac", "Terraform, OpenTofu, CloudFormation, Pulumi, CDK", 1.0),
            SkillCapability("config_mgmt", "Ansible, Puppet, Chef, SaltStack", 1.0),
            SkillCapability("monitoring", "Prometheus, Grafana, Datadog, New Relic, ELK stack", 1.0),
            SkillCapability("sre", "SLIs, SLOs, error budgets, incident response, runbooks", 1.0),
        ]

    async def _execute_analyse(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(suggestions=["Review CI pipeline performance", "Check IaC state management", "Verify monitoring coverage"])

    async def _execute_plan(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# DevOps Execution Plan\n\n1. Set up CI/CD pipeline (GitHub Actions)\n2. Configure IaC with Terraform\n3. Implement monitoring (Prometheus + Grafana)\n4. Set up logging (ELK/Loki)\n5. Create incident response runbooks\n6. Implement SLO tracking\n7. Configure alerting")

    async def _execute_review(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# DevOps Code Review\n\n## CI/CD\n- Parallel job execution\n- Cache dependencies\n- Security scanning in pipeline\n- Artifact management\n## IaC (Terraform)\n- Remote state with locking\n- Module structure\n- Resource tagging\n- Drift detection\n## Monitoring\n- Key metrics collected\n- Dashboard for each service\n- Alert thresholds configured\n- Log aggregation centralized\n## SRE\n- SLOs defined\n- Error budgets tracked\n- Postmortem process")

    async def _execute_generate(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Generated by DevOps Expert\nname: CI/CD\non:\n  push:\n    branches: [main]\n  pull_request:\n    branches: [main]\n\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - name: Run tests\n        run: |\n          npm ci\n          npm test\n  deploy:\n    needs: test\n    if: github.ref == 'refs/heads/main'\n    runs-on: ubuntu-latest\n    steps:\n      - name: Deploy\n        run: echo \"Deploying...\"")

    async def _execute_refactor(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# DevOps Refactoring\n\n1. Optimize CI pipeline for speed\n2. Modularize Terraform code\n3. Consolidate monitoring dashboards\n4. Automate incident response\n5. Implement GitOps with ArgoCD")

    async def _execute_debug(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# DevOps Debug Analysis\n\n## Common Issues\n- Pipeline failures\n- Terraform state drift\n- Configuration drift\n- Monitoring gaps\n## Tools\n- GitHub Actions logs\n- Terraform plan\n- Ansible --check\n- Prometheus queries\n- Grafana dashboards")

    async def _execute_explain(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# DevOps Explanation\n\nDevOps is a set of practices combining software development and IT operations, emphasizing automation, CI/CD, IaC, monitoring, and collaboration.")


class DevOpsExpert:
    DevOps = DevOpsExpertPack
