"""
Django Expert Skill Pack — domain expertise for Django framework.
"""

from __future__ import annotations

import logging

from backend.modules.coding_agent.skills._types import (
    SkillCapability,
    SkillMetadata,
    SkillResult,
)
from backend.modules.coding_agent.skills.context._models import SkillContext
from backend.modules.coding_agent.skills.packs._base import BaseSkillPack

_LOG = logging.getLogger("naira.coding_agent.skills.packs.django")


class DjangoExpertPack(BaseSkillPack):
    def __init__(self, *, logger: logging.Logger | None = None) -> None:
        super().__init__(
            logger=logger,
            metadata=SkillMetadata(
                name="Django Expert",
                description="Domain expert for Django — models, views, ORM, DRF, async, admin",
                supported_languages=("python",),
                supported_frameworks=("django", "django-rest-framework"),
                supported_file_extensions=(".py", ".html"),
                priority=75,
            ),
        )

    def _default_capabilities(self) -> list[SkillCapability]:
        return [
            SkillCapability("models", "Model definition, relationships, migrations, Meta class", 1.0),
            SkillCapability("orm", "QuerySet API, aggregation, select_related, prefetch_related", 1.0),
            SkillCapability("views", "FBV, CBV, ViewSets, generics, permissions", 1.0),
            SkillCapability("drf", "Django REST Framework, serializers, routers, authentication", 1.0),
            SkillCapability("admin", "Admin customization, actions, inlines, list display", 0.9),
        ]

    async def _execute_analyse(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(suggestions=["Review N+1 queries", "Check migration hygiene", "Verify permission classes"])

    async def _execute_plan(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Django Execution Plan\n\n1. Define models with proper relationships\n2. Create migrations\n3. Implement views (CBV/ViewSets)\n4. Add serializers for API\n5. Configure URL routing\n6. Add admin customization\n7. Write tests (pytest-django)")

    async def _execute_review(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Django Code Review\n\n## Models\n- Proper indexes\n- Verbose names\n- Soft delete patterns\n## ORM\n- select_related for FK\n- prefetch_related for M2M\n- No N+1 queries\n## Views\n- CBV for complex views\n- Permission checks\n- Proper HTTP methods\n## DRF\n- Serializer validation\n- Pagination\n- Throttling")

    async def _execute_generate(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Generated by Django Expert\nfrom django.db import models\nfrom django.contrib.auth import get_user_model\n\n\nclass Article(models.Model):\n    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='articles')\n    title = models.CharField(max_length=200)\n    body = models.TextField()\n    created_at = models.DateTimeField(auto_now_add=True)\n    updated_at = models.DateTimeField(auto_now=True)\n\n    class Meta:\n        ordering = ['-created_at']\n        indexes = [\n            models.Index(fields=['-created_at']),\n        ]\n\n    def __str__(self) -> str:\n        return self.title")

    async def _execute_refactor(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Django Refactoring\n\n1. Replace FBV with CBV/ViewSets\n2. Add select_related/prefetch_related\n3. Extract manager methods\n4. Add model properties\n5. Create service layer")

    async def _execute_debug(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Django Debug Analysis\n\n## Common Issues\n- N+1 queries\n- Migration conflicts\n- Permission issues\n- Template context bugs\n## Tools\n- Django Debug Toolbar\n- django-extensions\n- SQL logging")

    async def _execute_explain(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Django Explanation\n\nDjango is a high-level Python web framework that follows the battery-included philosophy, providing ORM, admin, auth, and templating out of the box.")


class DjangoExpert:
    Django = DjangoExpertPack
