"""
Docker Expert Skill Pack — domain expertise for Docker.
"""

from __future__ import annotations

import logging

from backend.modules.coding_agent.skills._types import (
    SkillCapability,
    SkillMetadata,
    SkillResult,
)
from backend.modules.coding_agent.skills.context._models import SkillContext
from backend.modules.coding_agent.skills.packs._base import BaseSkillPack

_LOG = logging.getLogger("naira.coding_agent.skills.packs.docker")


class DockerExpertPack(BaseSkillPack):
    def __init__(self, *, logger: logging.Logger | None = None) -> None:
        super().__init__(
            logger=logger,
            metadata=SkillMetadata(
                name="Docker Expert",
                description="Domain expert for Docker — Dockerfiles, compose, multi-stage builds, security scanning, orchestration",
                supported_languages=(),
                supported_frameworks=(),
                supported_file_extensions=(".dockerfile", ".dockerignore", ".yml", ".yaml"),
                priority=70,
            ),
        )

    def _default_capabilities(self) -> list[SkillCapability]:
        return [
            SkillCapability("dockerfile", "Multi-stage builds, layer caching, best practices", 1.0),
            SkillCapability("compose", "Docker Compose, services, networks, volumes, profiles", 1.0),
            SkillCapability("networking", "Bridge, host, overlay, Macvlan, DNS, expose ports", 0.9),
            SkillCapability("security", "Image scanning, non-root user, secrets, content trust", 1.0),
            SkillCapability("optimization", "Layer optimization, .dockerignore, slim images, distroless", 1.0),
        ]

    async def _execute_analyse(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(suggestions=["Review layer caching strategy", "Check security scanning", "Verify base image selection"])

    async def _execute_plan(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Docker Execution Plan\n\n1. Write optimized Dockerfile (multi-stage)\n2. Use distroless or alpine base images\n3. Set up .dockerignore\n4. Configure Docker Compose for services\n5. Add healthcheck\n6. Implement security scanning\n7. Set up container registry")

    async def _execute_review(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Docker Code Review\n\n## Dockerfile\n- Multi-stage builds for smaller images\n- Layer ordering for cache efficiency\n- COPY --chown for security\n- HEALTHCHECK instruction\n## Compose\n- Named volumes for data\n- Networks for isolation\n- Restart policies\n## Security\n- Non-root user\n- No secrets in build args\n- Image scanning (Trivy)\n- Pin base image versions")

    async def _execute_generate(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Generated by Docker Expert\nFROM node:20-alpine AS builder\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci --only=production\nCOPY . .\n\nFROM node:20-alpine\nWORKDIR /app\nRUN addgroup -S appgroup && adduser -S appuser -G appgroup\nCOPY --from=builder --chown=appuser:appgroup /app /app\nUSER appuser\nEXPOSE 3000\nHEALTHCHECK --interval=30s CMD wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1\nCMD [\"node\", \"server.js\"]")

    async def _execute_refactor(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Docker Refactoring\n\n1. Convert to multi-stage builds\n2. Reduce image size\n3. Add healthcheck\n4. Implement .dockerignore\n5. Upgrade base images\n6. Add non-root user")

    async def _execute_debug(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Docker Debug Analysis\n\n## Common Issues\n- Large image size\n- Layer cache invalidation\n- Permission denied\n- Network connectivity\n## Commands\n- docker build --no-cache\n- docker exec -it\n- docker logs\n- docker inspect\n- docker stats")

    async def _execute_explain(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Docker Explanation\n\nDocker is a containerization platform that packages applications with their dependencies into lightweight, portable containers.")


class DockerExpert:
    Docker = DockerExpertPack
