"""
DSA Expert Skill Pack — domain expertise for Data Structures and Algorithms.
"""

from __future__ import annotations

import logging

from backend.modules.coding_agent.skills._types import (
    SkillCapability,
    SkillMetadata,
    SkillResult,
)
from backend.modules.coding_agent.skills.context._models import SkillContext
from backend.modules.coding_agent.skills.packs._base import BaseSkillPack

_LOG = logging.getLogger("naira.coding_agent.skills.packs.dsa")


class DSAExpertPack(BaseSkillPack):
    def __init__(self, *, logger: logging.Logger | None = None) -> None:
        super().__init__(
            logger=logger,
            metadata=SkillMetadata(
                name="DSA Expert",
                description="Domain expert for Data Structures and Algorithms — complexity analysis, problem patterns, optimisation",
                supported_languages=(),
                supported_frameworks=(),
                supported_file_extensions=(),
                priority=50,
            ),
        )

    def _default_capabilities(self) -> list[SkillCapability]:
        return [
            SkillCapability("complexity_analysis", "Big O analysis, time/space trade-offs, amortized analysis", 1.0),
            SkillCapability("data_structures", "Arrays, linked lists, trees, graphs, hash tables, heaps, tries", 1.0),
            SkillCapability("algorithms", "Sorting, searching, graph algorithms, DP, greedy, divide & conquer", 1.0),
            SkillCapability("problem_patterns", "Two pointers, sliding window, backtracking, topological sort", 1.0),
            SkillCapability("optimization", "Algorithm optimization, space-time tradeoff, cache-friendly design", 1.0),
        ]

    async def _execute_analyse(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(suggestions=["Analyse time complexity (Big O)", "Consider alternative data structures", "Check for redundant computations"])

    async def _execute_plan(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# DSA Execution Plan\n\n1. Identify problem pattern (DP, Graph, Greedy, etc.)\n2. Choose appropriate data structures\n3. Design algorithm with optimal complexity\n4. Implement with edge cases\n5. Analyse time and space complexity\n6. Add test cases (normal, edge, large)")

    async def _execute_review(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# DSA Code Review\n\n## Complexity\n- Time: O(n log n) or better?\n- Space: In-place where possible?\n- Stack overflow risk?\n## Correctness\n- Edge cases handled (empty, single, duplicates)\n- Integer overflow considered\n- Recursion depth bounded\n## Optimization\n- Early termination conditions\n- Memoization for overlapping subproblems\n- Tail recursion where applicable")

    async def _execute_generate(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Generated by DSA Expert\ndef binary_search(arr: list[int], target: int) -> int:\n    left, right = 0, len(arr) - 1\n    while left <= right:\n        mid = left + (right - left) // 2\n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            left = mid + 1\n        else:\n            right = mid - 1\n    return -1")

    async def _execute_refactor(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# DSA Refactoring\n\n1. Optimize nested loops\n2. Replace recursion with iteration\n3. Use appropriate data structures\n4. Add memoization\n5. Reduce space complexity")

    async def _execute_debug(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# DSA Debug Analysis\n\n## Common Issues\n- Off-by-one errors\n- Infinite loops\n- Stack overflow from recursion\n- Unintended side effects\n## Techniques\n- Trace through small examples\n- Add assertions\n- Unit test edge cases\n- Profile for bottlenecks")

    async def _execute_explain(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# DSA Explanation\n\nData Structures & Algorithms is the foundation of computer science, covering efficient data organization and algorithmic problem-solving techniques.")


class DSAExpert:
    DSA = DSAExpertPack
