"""
Express Expert Skill Pack — domain expertise for Express.js framework.
"""

from __future__ import annotations

import logging

from backend.modules.coding_agent.skills._types import (
    SkillCapability,
    SkillMetadata,
    SkillResult,
)
from backend.modules.coding_agent.skills.context._models import SkillContext
from backend.modules.coding_agent.skills.packs._base import BaseSkillPack

_LOG = logging.getLogger("naira.coding_agent.skills.packs.express")


class ExpressExpertPack(BaseSkillPack):
    def __init__(self, *, logger: logging.Logger | None = None) -> None:
        super().__init__(
            logger=logger,
            metadata=SkillMetadata(
                name="Express Expert",
                description="Domain expert for Express.js — middleware, routing, error handling, security",
                supported_languages=("javascript", "typescript"),
                supported_frameworks=("express",),
                supported_file_extensions=(".js", ".ts", ".mjs"),
                priority=75,
            ),
        )

    def _default_capabilities(self) -> list[SkillCapability]:
        return [
            SkillCapability("middleware", "Middleware chain, error middleware, third-party middleware (helmet, cors, morgan)", 1.0),
            SkillCapability("routing", "Router, route parameters, query params, RESTful design", 1.0),
            SkillCapability("error_handling", "Centralized error handling, async error wrapping, custom errors", 1.0),
            SkillCapability("security_express", "Helmet, CORS, rate limiting, input validation, XSS protection", 1.0),
            SkillCapability("testing_express", "supertest, Jest, integration testing", 0.9),
        ]

    async def _execute_analyse(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(suggestions=["Add centralized error handler", "Verify security middleware", "Check route organization"])

    async def _execute_plan(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Express.js Execution Plan\n\n1. Set up project with ESM\n2. Configure middleware stack (helmet, cors, morgan, rate-limit)\n3. Implement route modules\n4. Add centralized error handling\n5. Add request validation (express-validator/zod)\n6. Add testing with supertest")

    async def _execute_review(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Express.js Code Review\n\n## Middleware\n- Helmet for security headers\n- CORS configured properly\n- Rate limiting enabled\n- Body parser limits set\n## Routes\n- RESTful naming conventions\n- Proper HTTP methods\n- Route parameters validated\n## Error Handling\n- Global error middleware\n- Async error wrapper\n- Consistent error responses")

    async def _execute_generate(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="// Generated by Express Expert\nimport express, { Request, Response, NextFunction } from 'express';\n\nexport const createApp = () => {\n  const app = express();\n  \n  app.use(express.json({ limit: '1mb' }));\n  \n  app.get('/api/health', (_req: Request, res: Response) => {\n    res.json({ status: 'healthy', timestamp: new Date().toISOString() });\n  });\n  \n  app.use((err: Error, _req: Request, res: Response, _next: NextFunction) => {\n    res.status(500).json({ error: err.message });\n  });\n  \n  return app;\n};")

    async def _execute_refactor(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Express.js Refactoring\n\n1. Extract route handlers to controllers\n2. Add middleware modules\n3. Implement async error wrapper\n4. Add request validation layer\n5. Centralize error handling")

    async def _execute_debug(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Express.js Debug Analysis\n\n## Common Issues\n- Unhandled async errors\n- Missing error middleware\n- CORS configuration\n- Body parser limits\n## Tools\n- debug package\n- morgan for logging\n- express-status-monitor")

    async def _execute_explain(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Express.js Explanation\n\nExpress is a minimal, unopinionated web framework for Node.js, providing HTTP utilities, middleware-based routing, and template engine integration.")


class ExpressExpert:
    Express = ExpressExpertPack
