"""
FastAPI Expert Skill Pack — domain expertise for FastAPI framework.
"""

from __future__ import annotations

import logging

from backend.modules.coding_agent.skills._types import (
    SkillCapability,
    SkillMetadata,
    SkillResult,
)
from backend.modules.coding_agent.skills.context._models import SkillContext
from backend.modules.coding_agent.skills.packs._base import BaseSkillPack

_LOG = logging.getLogger("naira.coding_agent.skills.packs.fastapi")


class FastAPIExpertPack(BaseSkillPack):
    def __init__(self, *, logger: logging.Logger | None = None) -> None:
        super().__init__(
            logger=logger,
            metadata=SkillMetadata(
                name="FastAPI Expert",
                description="Domain expert for FastAPI — async, Pydantic, dependency injection, OpenAPI",
                supported_languages=("python",),
                supported_frameworks=("fastapi",),
                supported_file_extensions=(".py",),
                priority=75,
            ),
        )

    def _default_capabilities(self) -> list[SkillCapability]:
        return [
            SkillCapability("routing", "Path operations, parameters, validators, routers", 1.0),
            SkillCapability("pydantic", "Model validation, settings management, schema generation", 1.0),
            SkillCapability("dependency_injection", "Depends, dependencies, yield fixtures, override", 1.0),
            SkillCapability("async_fastapi", "Async handlers, background tasks, streaming, WebSockets", 1.0),
            SkillCapability("testing_fastapi", "TestClient, pytest, async tests, fixture overrides", 0.9),
        ]

    async def _execute_analyse(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(suggestions=["Review dependency injection patterns", "Check Pydantic model validation", "Verify async handler usage"])

    async def _execute_plan(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# FastAPI Execution Plan\n\n1. Define Pydantic schemas (request/response)\n2. Create path operation functions\n3. Implement dependency injection\n4. Add route-level validation\n5. Configure OpenAPI metadata\n6. Add async database sessions\n7. Write tests with TestClient")

    async def _execute_review(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# FastAPI Code Review\n\n## Schemas\n- Pydantic v2 models\n- Config for ORM mode\n- Proper validators\n## Routes\n- Correct status codes\n- Response models\n- Dependencies for auth\n## Async\n- Async database sessions\n- Background tasks\n- Proper await usage\n## Testing\n- TestClient overrides\n- Async tests with pytest")

    async def _execute_generate(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Generated by FastAPI Expert\nfrom fastapi import FastAPI, Depends, HTTPException\nfrom pydantic import BaseModel\n\napp = FastAPI(title=\"API\", version=\"1.0.0\")\n\nclass Item(BaseModel):\n    name: str\n    price: float\n\n@app.get(\"/items/{item_id}\", response_model=Item)\nasync def get_item(item_id: int):\n    return Item(name=\"Example\", price=9.99)")

    async def _execute_refactor(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# FastAPI Refactoring\n\n1. Split routers into modules\n2. Extract dependency functions\n3. Add response models\n4. Implement proper error handling\n5. Add background tasks")

    async def _execute_debug(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# FastAPI Debug Analysis\n\n## Common Issues\n- Sync vs async mismatch\n- Pydantic validation errors\n- Dependency override issues\n- CORS configuration\n## Tools\n- /docs (Swagger)\n- /redoc\n- uvicorn --reload")

    async def _execute_explain(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# FastAPI Explanation\n\nFastAPI is a modern Python web framework for building APIs with automatic OpenAPI documentation, Pydantic validation, and async support.")


class FastAPIExpert:
    FastAPI = FastAPIExpertPack
