"""
Git Expert Skill Pack — domain expertise for Git version control.
"""

from __future__ import annotations

import logging

from backend.modules.coding_agent.skills._types import (
    SkillCapability,
    SkillMetadata,
    SkillResult,
)
from backend.modules.coding_agent.skills.context._models import SkillContext
from backend.modules.coding_agent.skills.packs._base import BaseSkillPack

_LOG = logging.getLogger("naira.coding_agent.skills.packs.git")


class GitExpertPack(BaseSkillPack):
    def __init__(self, *, logger: logging.Logger | None = None) -> None:
        super().__init__(
            logger=logger,
            metadata=SkillMetadata(
                name="Git Expert",
                description="Domain expert for Git — branching, rebasing, CI/CD, hooks, workflows (GitHub Flow, Git Flow)",
                supported_languages=(),
                supported_frameworks=(),
                supported_file_extensions=(".gitignore", ".gitattributes", ".gitmodules", ".gitkeep", ".md"),
                priority=60,
            ),
        )

    def _default_capabilities(self) -> list[SkillCapability]:
        return [
            SkillCapability("branching", "Branch strategies, feature branches, Git Flow, trunk-based", 1.0),
            SkillCapability("rebasing", "Interactive rebase, conflict resolution, commit squashing", 1.0),
            SkillCapability("hooks", "pre-commit, pre-push, commit-msg hooks", 1.0),
            SkillCapability("workflows", "GitHub Flow, Git Flow, forking workflow, monorepo strategies", 1.0),
            SkillCapability("ci_integration", "GitHub Actions, GitLab CI, pre-commit CI", 0.9),
        ]

    async def _execute_analyse(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(suggestions=["Review branching strategy", "Check .gitignore completeness", "Verify CI pipeline setup"])

    async def _execute_plan(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Git Workflow Plan\n\n1. Choose branching strategy (GitHub Flow recommended)\n2. Set up .gitignore\n3. Configure pre-commit hooks\n4. Set up branch protection rules\n5. Implement CI pipeline\n6. Establish commit message convention")

    async def _execute_review(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Git Code Review\n\n## Commits\n- Conventional commits format\n- Atomic commits (one change per commit)\n- Descriptive messages\n## Branching\n- Feature branches from main\n- Regular rebase on main\n- Delete merged branches\n## CI/CD\n- Pre-commit hooks configured\n- Automated tests on push\n- Branch protection enabled\n## Security\n- No secrets in commits\n- .gitignore for sensitive files")

    async def _execute_generate(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Generated by Git Expert\n# .gitignore\n__pycache__/\n*.py[cod]\n*.egg-info/\nnode_modules/\n.env\nvenv/\n.idea/\n*.log\n.DS_Store")

    async def _execute_refactor(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Git Refactoring\n\n1. Clean up .gitignore\n2. Add .gitattributes for line endings\n3. Configure pre-commit hooks\n4. Set up branch protection\n5. Add CI/CD workflow")

    async def _execute_debug(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Git Debug Analysis\n\n## Common Issues\n- Merge conflicts\n- Detached HEAD\n- Lost commits\n- Large files in history\n## Commands\n- git bisect\n- git reflog\n- git blame\n- git cherry-pick")

    async def _execute_explain(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Git Explanation\n\nGit is a distributed version control system for tracking changes in source code, supporting branching, merging, and collaboration workflows.")


class GitExpert:
    Git = GitExpertPack
