"""
Java Expert Skill Pack — domain expertise for Java.
"""

from __future__ import annotations

import logging

from backend.modules.coding_agent.skills._types import (
    SkillCapability,
    SkillMetadata,
    SkillResult,
)
from backend.modules.coding_agent.skills.context._models import SkillContext
from backend.modules.coding_agent.skills.packs._base import BaseSkillPack

_LOG = logging.getLogger("naira.coding_agent.skills.packs.java")


class JavaExpertPack(BaseSkillPack):
    def __init__(self, *, logger: logging.Logger | None = None) -> None:
        super().__init__(
            logger=logger,
            metadata=SkillMetadata(
                name="Java Expert",
                description="Domain expert for Java — JVM, concurrency, Spring, Maven/Gradle",
                supported_languages=("java",),
                supported_frameworks=("spring", "spring-boot", "hibernate", "jakarta"),
                supported_file_extensions=(".java", ".class", ".jar", ".jmod"),
                priority=80,
            ),
        )

    def _default_capabilities(self) -> list[SkillCapability]:
        return [
            SkillCapability("java_modern", "Java 8 through 21 features (records, sealed classes, pattern matching)", 1.0),
            SkillCapability("jvm", "JVM internals, garbage collection, JIT compilation", 1.0),
            SkillCapability("concurrency", "java.util.concurrent, virtual threads (Loom)", 1.0),
            SkillCapability("spring", "Spring Boot, Spring MVC, Spring Data, Spring Security", 1.0),
            SkillCapability("build_tools", "Maven, Gradle, build optimization", 0.9),
        ]

    async def _execute_analyse(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(suggestions=["Check JVM version compatibility", "Review exception handling", "Verify thread safety"])

    async def _execute_plan(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Java Execution Plan\n\n1. Design interfaces and abstractions\n2. Implement with records and sealed classes\n3. Add comprehensive unit tests (JUnit 5)\n4. Configure build with Maven/Gradle\n5. Add error handling with custom exceptions\n6. Document with Javadoc")

    async def _execute_review(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Java Code Review\n\n## Modern Java\n- Use records for data carriers\n- Prefer Optional over null\n- Use Stream API\n- Pattern matching for instanceof\n## Concurrency\n- Virtual threads for Loom\n- Concurrent collections\n- Avoid synchronized blocks\n## Build\n- Gradle for modern projects\n- Maven for enterprise")

    async def _execute_generate(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="// Generated by Java Expert\npublic sealed interface Result<T> permits Success, Failure {\n    <U> Result<U> map(java.util.function.Function<T, U> fn);\n}\n\nrecord Success<T>(T value) implements Result<T> {\n    @Override\n    public <U> Result<U> map(java.util.function.Function<T, U> fn) {\n        return new Success<>(fn.apply(value));\n    }\n}")

    async def _execute_refactor(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Java Refactoring\n\n1. Replace anonymous classes with lambdas\n2. Replace if-else with pattern matching\n3. Add records for data classes\n4. Replace null checks with Optional\n5. Extract interfaces\n6. Add sealed hierarchies")

    async def _execute_debug(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Java Debug Analysis\n\n## Common Issues\n- NullPointerException\n- ConcurrentModificationException\n- Memory leaks\n- ClassLoader issues\n- Thread deadlocks\n## Tools\n- IntelliJ debugger\n- JProfiler\n- VisualVM\n- JDK Flight Recorder")

    async def _execute_explain(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Java Explanation\n\nJava is a statically-typed, class-based OOP language running on the JVM. Modern Java (17+) features records, sealed classes, pattern matching, and virtual threads.")


class JavaExpert:
    Java = JavaExpertPack
