"""
JavaScript Expert Skill Pack — domain expertise for JavaScript.
"""

from __future__ import annotations

import logging

from backend.modules.coding_agent.skills._types import (
    SkillCapability,
    SkillMetadata,
    SkillResult,
)
from backend.modules.coding_agent.skills.context._models import SkillContext
from backend.modules.coding_agent.skills.packs._base import BaseSkillPack

_LOG = logging.getLogger("naira.coding_agent.skills.packs.javascript")


class JavaScriptExpertPack(BaseSkillPack):
    def __init__(self, *, logger: logging.Logger | None = None) -> None:
        super().__init__(
            logger=logger,
            metadata=SkillMetadata(
                name="JavaScript Expert",
                description="Domain expert for JavaScript — ES6+, async, DOM, Node.js, testing",
                supported_languages=("javascript",),
                supported_frameworks=("express", "react", "vue", "angular"),
                supported_file_extensions=(".js", ".mjs", ".cjs", ".jsx"),
                priority=80,
            ),
        )

    def _default_capabilities(self) -> list[SkillCapability]:
        return [
            SkillCapability("es6_plus", "ES6+ features: arrow functions, destructuring, spread, modules", 1.0),
            SkillCapability("async_js", "Promises, async/await, event loop, microtasks", 1.0),
            SkillCapability("dom_api", "DOM manipulation, events, Web APIs", 0.9),
            SkillCapability("testing_js", "Jest, Mocha, Vitest, Cypress", 0.9),
            SkillCapability("bundlers", "Webpack, Vite, ESBuild, Rollup", 0.9),
        ]

    async def _execute_analyse(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(suggestions=["Check async error handling", "Review bundle size", "Verify polyfill usage"])

    async def _execute_plan(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# JavaScript Execution Plan\n\n1. Define module structure (ESM)\n2. Implement with async/await\n3. Add error boundaries\n4. Configure bundler (Vite)\n5. Add Jest/Vitest tests\n6. Set up ESLint + Prettier")

    async def _execute_review(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# JavaScript Code Review\n\n## Modern JS\n- Use const/let over var\n- Use arrow functions for callbacks\n- Destructuring for object access\n- Nullish coalescing ??\n## Async\n- Proper error handling with try/catch\n- No unhandled promise rejections\n- Avoid callback patterns\n## Performance\n- Debounce/throttle events\n- Code splitting\n- Tree shaking")

    async def _execute_generate(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="// Generated by JavaScript Expert\nconst fetchData = async (url) => {\n  const response = await fetch(url);\n  if (!response.ok) throw new Error(`HTTP ${response.status}`);\n  return response.json();\n};\n\nexport { fetchData };")

    async def _execute_refactor(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# JavaScript Refactoring\n\n1. Replace var with const/let\n2. Convert callbacks to async/await\n3. Use destructuring\n4. Extract constants\n5. Add JSDoc annotations\n6. Split large functions")

    async def _execute_debug(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# JavaScript Debug Analysis\n\n## Common Issues\n- Undefined is not a function\n- Promise unhandled rejection\n- Closure memory leaks\n- Event loop starvation\n## Tools\n- Chrome DevTools\n- Node --inspect\n- Sentry\n- console.time")

    async def _execute_explain(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# JavaScript Explanation\n\nJavaScript is a dynamic, prototype-based language powering the web. Modern JS (ES6+) features modules, promises, classes, and arrow functions.")


class JavaScriptExpert:
    JS = JavaScriptExpertPack
