"""
Kubernetes Expert Skill Pack — domain expertise for Kubernetes.
"""

from __future__ import annotations

import logging

from backend.modules.coding_agent.skills._types import (
    SkillCapability,
    SkillMetadata,
    SkillResult,
)
from backend.modules.coding_agent.skills.context._models import SkillContext
from backend.modules.coding_agent.skills.packs._base import BaseSkillPack

_LOG = logging.getLogger("naira.coding_agent.skills.packs.kubernetes")


class KubernetesExpertPack(BaseSkillPack):
    def __init__(self, *, logger: logging.Logger | None = None) -> None:
        super().__init__(
            logger=logger,
            metadata=SkillMetadata(
                name="Kubernetes Expert",
                description="Domain expert for Kubernetes — pods, services, deployments, Helm, operators, security",
                supported_languages=(),
                supported_frameworks=(),
                supported_file_extensions=(".yaml", ".yml", ".tpl"),
                priority=70,
            ),
        )

    def _default_capabilities(self) -> list[SkillCapability]:
        return [
            SkillCapability("workloads", "Deployments, StatefulSets, DaemonSets, Jobs, CronJobs", 1.0),
            SkillCapability("networking_k8s", "Services, Ingress, NetworkPolicies, CNI plugins", 1.0),
            SkillCapability("storage", "PersistentVolumes, PVCs, StorageClasses, CSI", 1.0),
            SkillCapability("helm", "Helm charts, templates, values, hooks, dependencies", 1.0),
            SkillCapability("security_k8s", "RBAC, PodSecurity, secrets, ServiceAccounts, OPA/Gatekeeper", 1.0),
            SkillCapability("operators", "Custom Resource Definitions, operators, controllers", 0.8),
        ]

    async def _execute_analyse(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(suggestions=["Review resource requests/limits", "Check RBAC configuration", "Verify pod security context"])

    async def _execute_plan(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Kubernetes Execution Plan\n\n1. Define Deployments with resource limits\n2. Create Services for internal/external access\n3. Configure Ingress for routing\n4. Set up ConfigMaps and Secrets\n5. Implement RBAC\n6. Add NetworkPolicies\n7. Package as Helm chart\n8. Configure monitoring (Prometheus)")

    async def _execute_review(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Kubernetes Code Review\n\n## Workloads\n- Resource requests/limits set\n- Liveness/readiness probes\n- Pod disruption budgets\n- Anti-affinity rules\n## Security\n- Pod Security Standards\n- NetworkPolicy for zero-trust\n- Secrets not in env vars\n- Non-root containers\n## Configuration\n- ConfigMaps for non-sensitive config\n- Secrets for sensitive data\n- Helm for packaging\n- kustomize for overlays")

    async def _execute_generate(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Generated by Kubernetes Expert\napiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: app\n  labels:\n    app: app\nspec:\n  replicas: 3\n  selector:\n    matchLabels:\n      app: app\n  template:\n    metadata:\n      labels:\n        app: app\n    spec:\n      securityContext:\n        runAsNonRoot: true\n        runAsUser: 1001\n      containers:\n      - name: app\n        image: app:latest\n        ports:\n        - containerPort: 3000\n        resources:\n          requests:\n            cpu: 100m\n            memory: 128Mi\n          limits:\n            cpu: 500m\n            memory: 256Mi\n        livenessProbe:\n          httpGet:\n            path: /health\n            port: 3000")

    async def _execute_refactor(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Kubernetes Refactoring\n\n1. Add resource limits\n2. Implement NetworkPolicies\n3. Convert to Helm chart\n4. Add pod anti-affinity\n5. Upgrade deprecated APIs\n6. Implement GitOps workflow")

    async def _execute_debug(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Kubernetes Debug Analysis\n\n## Common Issues\n- Pod CrashLoopBackOff\n- ImagePullBackOff\n- Resource exhaustion\n- Network policy blocking\n## Commands\n- kubectl describe pod\n- kubectl logs\n- kubectl exec\n- kubectl top\n## Tools\n- k9s\n- stern\n- kubectx\n- Lens")

    async def _execute_explain(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Kubernetes Explanation\n\nKubernetes is an open-source container orchestration platform for automating deployment, scaling, and management of containerized applications.")


class KubernetesExpert:
    K8s = KubernetesExpertPack
