"""
Linux Expert Skill Pack — domain expertise for Linux systems.
"""

from __future__ import annotations

import logging

from backend.modules.coding_agent.skills._types import (
    SkillCapability,
    SkillMetadata,
    SkillResult,
)
from backend.modules.coding_agent.skills.context._models import SkillContext
from backend.modules.coding_agent.skills.packs._base import BaseSkillPack

_LOG = logging.getLogger("naira.coding_agent.skills.packs.linux")


class LinuxExpertPack(BaseSkillPack):
    def __init__(self, *, logger: logging.Logger | None = None) -> None:
        super().__init__(
            logger=logger,
            metadata=SkillMetadata(
                name="Linux Expert",
                description="Domain expert for Linux — shell scripting, system administration, performance tuning, security hardening",
                supported_languages=("bash", "shell", "sh"),
                supported_frameworks=(),
                supported_file_extensions=(".sh", ".bash", ".zsh", ".env", ".conf", ".service"),
                priority=60,
            ),
        )

    def _default_capabilities(self) -> list[SkillCapability]:
        return [
            SkillCapability("shell_scripting", "Bash scripting, POSIX sh, error handling, debugging", 1.0),
            SkillCapability("system_admin", "Process management, systemd, users/groups, filesystem, LVM", 1.0),
            SkillCapability("performance", "CPU profiling, memory analysis, I/O tuning, sysctl", 1.0),
            SkillCapability("security_hardening", "SELinux/AppArmor, firewall, SSH hardening, auditd", 1.0),
            SkillCapability("networking_linux", "iptables/nftables, tcpdump, ss, netstat, routing", 0.9),
        ]

    async def _execute_analyse(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(suggestions=["Check system resource usage", "Review security hardening", "Verify backup strategy"])

    async def _execute_plan(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Linux Execution Plan\n\n1. Harden SSH configuration\n2. Set up firewall (ufw/nftables)\n3. Configure log rotation\n4. Set up monitoring (Prometheus node_exporter)\n5. Implement backup strategy\n6. Configure automated security updates")

    async def _execute_review(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Linux Code Review\n\n## Shell Scripts\n- Use set -euo pipefail\n- Quote all variables\n- Check exit codes\n- Use functions for reuse\n## Security\n- SSH key-only auth\n- Disable root login\n- Fail2ban configured\n- Regular security updates\n## Performance\n- ulimits configured\n- swappiness tuned\n- I/O scheduler appropriate\n- Transparent hugepages configured")

    async def _execute_generate(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Generated by Linux Expert\n#!/usr/bin/env bash\nset -euo pipefail\n\nreadonly SCRIPT_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && pwd)\"\nreadonly LOG_FILE=\"/var/log/app.log\"\n\nlog() {\n    local level=\"${1:-INFO}\"\n    shift\n    echo \"[$(date '+%Y-%m-%d %H:%M:%S')] [${level}] $*\" >> \"${LOG_FILE}\"\n}\n\ncleanup() {\n    log \"INFO\" \"Cleaning up...\"\n}\ntrap cleanup EXIT\n\nlog \"INFO\" \"Starting...\"")

    async def _execute_refactor(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Linux Refactoring\n\n1. Add error handling to scripts\n2. Replace systemd with better units\n3. Optimize kernel parameters\n4. Harden via CIS benchmarks\n5. Add monitoring agents")

    async def _execute_debug(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Linux Debug Analysis\n\n## Common Issues\n- Out of memory (OOM)\n- Disk space full\n- File descriptor limits\n- Permission denied\n## Commands\n- dmesg\n- journalctl\n- strace\n- lsof\n- perf\n- iostat")

    async def _execute_explain(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Linux Explanation\n\nLinux is a Unix-like open-source operating system kernel powering servers, desktops, and embedded systems worldwide.")


class LinuxExpert:
    Linux = LinuxExpertPack
