"""
MongoDB Expert Skill Pack — domain expertise for MongoDB.
"""

from __future__ import annotations

import logging

from backend.modules.coding_agent.skills._types import (
    SkillCapability,
    SkillMetadata,
    SkillResult,
)
from backend.modules.coding_agent.skills.context._models import SkillContext
from backend.modules.coding_agent.skills.packs._base import BaseSkillPack

_LOG = logging.getLogger("naira.coding_agent.skills.packs.mongodb")


class MongoDBExpertPack(BaseSkillPack):
    def __init__(self, *, logger: logging.Logger | None = None) -> None:
        super().__init__(
            logger=logger,
            metadata=SkillMetadata(
                name="MongoDB Expert",
                description="Domain expert for MongoDB — aggregation pipeline, indexing, schema design, replication",
                supported_languages=("javascript", "python", "json"),
                supported_frameworks=(),
                supported_file_extensions=(".json", ".js", ".py"),
                priority=70,
            ),
        )

    def _default_capabilities(self) -> list[SkillCapability]:
        return [
            SkillCapability("aggregation", "Aggregation pipeline, $match, $group, $lookup, $unwind, $facet", 1.0),
            SkillCapability("indexing", "Single field, compound, multikey, text, geospatial, TTL", 1.0),
            SkillCapability("schema_design", "Document embedding, referencing, polymorphic schemas", 1.0),
            SkillCapability("replication", "Replica sets, read preference, write concern", 0.9),
            SkillCapability("sharding", "Sharding strategies, hashed sharding, zone sharding", 0.8),
        ]

    async def _execute_analyse(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(suggestions=["Review aggregation pipeline performance", "Check index usage", "Verify schema design patterns"])

    async def _execute_plan(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# MongoDB Execution Plan\n\n1. Design document schema\n2. Create appropriate indexes\n3. Build aggregation pipeline\n4. Configure read/write concerns\n5. Set up monitoring with profiler\n6. Implement backup strategy")

    async def _execute_review(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# MongoDB Code Review\n\n## Queries\n- Use covered queries\n- Proper index usage\n- Avoid regex without index\n## Aggregation\n- $match early to reduce documents\n- $lookup on indexed fields\n- Use $facet for complex reports\n## Schema\n- Embedding vs referencing\n- Appropriate data types\n- Use 2dsphere for geospatial")

    async def _execute_generate(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="// Generated by MongoDB Expert\ndb.users.createIndex({ email: 1 }, { unique: true });\ndb.orders.aggregate([\n  { $match: { status: 'completed' } },\n  { $group: { _id: '$userId', total: { $sum: '$amount' } } },\n  { $sort: { total: -1 } },\n  { $limit: 10 }\n]);")

    async def _execute_refactor(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# MongoDB Refactoring\n\n1. Add missing indexes\n2. Optimize aggregation pipelines\n3. Restructure embedded documents\n4. Use $lookup for complex joins\n5. Implement TTL indexes for expiry")

    async def _execute_debug(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# MongoDB Debug Analysis\n\n## Common Issues\n- Unindexed queries\n- Large aggregation memory\n- Document size > 16MB\n- Write concern timeout\n## Tools\n- mongostat\n- mongotop\n- Atlas profiler\n- explain()")

    async def _execute_explain(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# MongoDB Explanation\n\nMongoDB is a NoSQL document database storing JSON-like documents with dynamic schemas, offering powerful aggregation, indexing, and horizontal scaling.")


class MongoDBExpert:
    MongoDB = MongoDBExpertPack
