"""
Next.js Expert Skill Pack — domain expertise for Next.js.
"""

from __future__ import annotations

import logging

from backend.modules.coding_agent.skills._types import (
    SkillCapability,
    SkillMetadata,
    SkillResult,
)
from backend.modules.coding_agent.skills.context._models import SkillContext
from backend.modules.coding_agent.skills.packs._base import BaseSkillPack

_LOG = logging.getLogger("naira.coding_agent.skills.packs.nextjs")


class NextJsExpertPack(BaseSkillPack):
    def __init__(self, *, logger: logging.Logger | None = None) -> None:
        super().__init__(
            logger=logger,
            metadata=SkillMetadata(
                name="Next.js Expert",
                description="Domain expert for Next.js — App Router, SSR, ISR, middleware, API routes",
                supported_languages=("javascript", "typescript"),
                supported_frameworks=("nextjs", "react"),
                supported_file_extensions=(".jsx", ".tsx", ".js", ".ts"),
                priority=85,
            ),
        )

    def _default_capabilities(self) -> list[SkillCapability]:
        return [
            SkillCapability("app_router", "App Router, layouts, nested routes, loading states, error boundaries", 1.0),
            SkillCapability("rendering", "SSR, SSG, ISR, streaming, partial prerendering", 1.0),
            SkillCapability("data_fetching", "Server Components, server actions, revalidation", 1.0),
            SkillCapability("middleware", "Middleware, edge runtime, rewrite/redirect", 0.9),
            SkillCapability("optimization", "Image optimization, font optimization, metadata, SEO", 1.0),
        ]

    async def _execute_analyse(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(suggestions=["Use App Router over Pages Router", "Check data fetching strategy", "Verify caching behavior"])

    async def _execute_plan(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Next.js Execution Plan\n\n1. Design App Router structure with layouts\n2. Implement Server Components by default\n3. Add client interactivity where needed\n4. Configure data fetching strategy (SSR/SSG/ISR)\n5. Add middleware for auth/routing\n6. Optimize images and fonts\n7. Add metadata for SEO")

    async def _execute_review(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Next.js Code Review\n\n## App Router\n- Nested layouts for shared UI\n- loading.tsx for loading states\n- error.tsx for error boundaries\n- not-found.tsx for 404\n## Data Fetching\n- Use Server Components for initial data\n- Server Actions for mutations\n- Proper revalidation\n## Performance\n- next/image for images\n- next/font for fonts\n- Streaming with Suspense")

    async def _execute_generate(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="// Generated by Next.js Expert\nimport { Metadata } from 'next';\n\nexport const metadata: Metadata = {\n  title: 'Page Title',\n  description: 'Page description',\n};\n\nexport default async function Page() {\n  const data = await fetchData();\n  \n  return (\n    <main>\n      <h1>{data.title}</h1>\n      <p>{data.description}</p>\n    </main>\n  );\n}\n\nasync function fetchData() {\n  const res = await fetch('https://api.example.com/data', {\n    next: { revalidate: 3600 },\n  });\n  return res.json();\n}")

    async def _execute_refactor(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Next.js Refactoring\n\n1. Migrate Pages Router to App Router\n2. Convert getServerSideProps to Server Components\n3. Add Suspense boundaries\n4. Implement server actions for forms\n5. Add metadata API")

    async def _execute_debug(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Next.js Debug Analysis\n\n## Common Issues\n- Waterfall requests\n- Missing key in lists\n- Client/Server component mixing\n- Caching stale data\n## Tools\n- React DevTools\n- next/logger\n- Route segment config")

    async def _execute_explain(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Next.js Explanation\n\nNext.js is a React framework for production, providing SSR, SSG, ISR, App Router, and full-stack capabilities with Server Components and actions.")


class NextJsExpert:
    NextJS = NextJsExpertPack
