"""
Node.js Expert Skill Pack — domain expertise for Node.js runtime.
"""

from __future__ import annotations

import logging

from backend.modules.coding_agent.skills._types import (
    SkillCapability,
    SkillMetadata,
    SkillResult,
)
from backend.modules.coding_agent.skills.context._models import SkillContext
from backend.modules.coding_agent.skills.packs._base import BaseSkillPack

_LOG = logging.getLogger("naira.coding_agent.skills.packs.nodejs")


class NodeJsExpertPack(BaseSkillPack):
    def __init__(self, *, logger: logging.Logger | None = None) -> None:
        super().__init__(
            logger=logger,
            metadata=SkillMetadata(
                name="Node.js Expert",
                description="Domain expert for Node.js runtime — CommonJS/ESM, streams, clustering, npm/yarn/pnpm",
                supported_languages=("javascript", "typescript"),
                supported_frameworks=("express", "fastify", "nestjs"),
                supported_file_extensions=(".js", ".mjs", ".cjs", ".ts", ".json"),
                priority=80,
            ),
        )

    def _default_capabilities(self) -> list[SkillCapability]:
        return [
            SkillCapability("modules", "CommonJS, ESM, module resolution, interop", 1.0),
            SkillCapability("streams", "Readable, Writable, Transform, pipeline, backpressure", 1.0),
            SkillCapability("cluster", "Cluster module, worker_threads, child_process", 1.0),
            SkillCapability("npm_ecosystem", "npm, yarn, pnpm, package.json, workspaces", 1.0),
            SkillCapability("event_loop", "Event loop phases, microtasks, timers, nextTick", 1.0),
        ]

    async def _execute_analyse(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(suggestions=["Check memory usage", "Review error propagation", "Verify async patterns"])

    async def _execute_plan(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Node.js Execution Plan\n\n1. Choose module system (ESM preferred)\n2. Set up package.json with exports\n3. Implement with streams for I/O\n4. Add error handling with error codes\n5. Configure clustering for multi-core\n6. Add logger (pino/winston)")

    async def _execute_review(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Node.js Code Review\n\n## Module System\n- Use ESM for new projects\n- Package.json exports field\n- Proper import/export\n## Performance\n- Stream large files\n- Avoid synchronous APIs\n- Use worker_threads for CPU\n## Security\n- Input validation\n- Helmet for HTTP headers\n- Rate limiting")

    async def _execute_generate(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="// Generated by Node.js Expert\nimport { createServer } from 'node:http';\n\nconst server = createServer(async (req, res) => {\n  res.writeHead(200, { 'Content-Type': 'application/json' });\n  res.end(JSON.stringify({ status: 'ok', version: process.version }));\n});\n\nserver.listen(3000, () => {\n  console.log(`Server running on http://localhost:3000`);\n});")

    async def _execute_refactor(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Node.js Refactoring\n\n1. Convert require to import\n2. Add try/catch to async operations\n3. Use pipeline over pipe\n4. Replace callback-based with async/await\n5. Add proper error codes")

    async def _execute_debug(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Node.js Debug Analysis\n\n## Common Issues\n- Memory leaks from closures\n- Unhandled promise rejections\n- Event loop blocking\n- Socket hang-up\n## Tools\n- Node --inspect\n- clinic.js\n- 0x (flame graphs)\n- heapdump")

    async def _execute_explain(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Node.js Explanation\n\nNode.js is a JavaScript runtime built on V8, designed for scalable network applications. It uses an event-driven, non-blocking I/O model.")


class NodeJsExpert:
    NodeJS = NodeJsExpertPack
