"""
PostgreSQL Expert Skill Pack — domain expertise for PostgreSQL.
"""

from __future__ import annotations

import logging

from backend.modules.coding_agent.skills._types import (
    SkillCapability,
    SkillMetadata,
    SkillResult,
)
from backend.modules.coding_agent.skills.context._models import SkillContext
from backend.modules.coding_agent.skills.packs._base import BaseSkillPack

_LOG = logging.getLogger("naira.coding_agent.skills.packs.postgresql")


class PostgreSQLExpertPack(BaseSkillPack):
    def __init__(self, *, logger: logging.Logger | None = None) -> None:
        super().__init__(
            logger=logger,
            metadata=SkillMetadata(
                name="PostgreSQL Expert",
                description="Domain expert for PostgreSQL — advanced SQL, extensions, performance tuning, replication",
                supported_languages=("sql",),
                supported_frameworks=(),
                supported_file_extensions=(".sql", ".psql"),
                priority=80,
            ),
        )

    def _default_capabilities(self) -> list[SkillCapability]:
        return [
            SkillCapability("advanced_postgres", "CTEs, window functions, recursive queries, LATERAL, JSONB", 1.0),
            SkillCapability("performance", "EXPLAIN ANALYZE, vacuum, autovacuum, work_mem, shared_buffers", 1.0),
            SkillCapability("extensions", "PostGIS, pgvector, timescaledb, citus, pg_partman", 1.0),
            SkillCapability("replication", "Streaming replication, logical replication, failover", 0.9),
            SkillCapability("backup", "pg_dump, pg_basebackup, WAL archiving, PITR", 1.0),
        ]

    async def _execute_analyse(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(suggestions=["Check slow queries", "Review autovacuum settings", "Verify connection pooling"])

    async def _execute_plan(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# PostgreSQL Execution Plan\n\n1. Design schema with proper constraints\n2. Create indexes (B-tree, GIN, GiST, BRIN)\n3. Tune postgresql.conf parameters\n4. Set up connection pooling (PgBouncer)\n5. Configure backup strategy\n6. Implement monitoring")

    async def _execute_review(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# PostgreSQL Code Review\n\n## Queries\n- Use EXPLAIN ANALYZE\n- Leverage JSONB for flexible schemas\n- Use GIN indexes for JSONB/arrays\n## Configuration\n- shared_buffers = 25% of RAM\n- work_mem per operation\n- effective_cache_size\n## Extensions\n- pgvector for embeddings\n- PostGIS for geospatial\n- pg_stat_statements for monitoring")

    async def _execute_generate(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="-- Generated by PostgreSQL Expert\nCREATE TABLE events (\n    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n    event_type VARCHAR(50) NOT NULL,\n    payload JSONB NOT NULL,\n    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()\n) PARTITION BY RANGE (created_at);\n\nCREATE INDEX idx_events_type ON events (event_type);\nCREATE INDEX idx_events_payload ON events USING GIN (payload);")

    async def _execute_refactor(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# PostgreSQL Refactoring\n\n1. Partition large tables\n2. Add missing indexes\n3. Optimize with CTEs\n4. Use materialized views\n5. Implement table inheritance")

    async def _execute_debug(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# PostgreSQL Debug Analysis\n\n## Common Issues\n- Long-running queries\n- Deadlocks\n- VACUUM bloat\n- Connection pool exhaustion\n## Tools\n- pg_stat_activity\n- pg_stat_statements\n- auto_explain\n- pgBadger")

    async def _execute_explain(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# PostgreSQL Explanation\n\nPostgreSQL is an advanced open-source RDBMS with ACID compliance, extensibility, support for JSON, full-text search, and advanced indexing.")


class PostgreSQLExpert:
    PostgreSQL = PostgreSQLExpertPack
