"""
Python Expert Skill Pack — domain expertise for Python.
"""

from __future__ import annotations

import logging

from backend.modules.coding_agent.skills._types import (
    SkillCapability,
    SkillMetadata,
    SkillResult,
)
from backend.modules.coding_agent.skills.context._models import SkillContext
from backend.modules.coding_agent.skills.packs._base import BaseSkillPack

_LOG = logging.getLogger("naira.coding_agent.skills.packs.python")


class PythonExpertPack(BaseSkillPack):
    def __init__(self, *, logger: logging.Logger | None = None) -> None:
        super().__init__(
            logger=logger,
            metadata=SkillMetadata(
                name="Python Expert",
                description="Domain expert for Python — idioms, patterns, typing, async, testing, packaging",
                supported_languages=("python",),
                supported_frameworks=("django", "fastapi", "flask"),
                supported_file_extensions=(".py", ".pyi", ".pyx", ".pxd", ".pyw"),
                priority=90,
            ),
        )

    def _default_capabilities(self) -> list[SkillCapability]:
        return [
            SkillCapability("python_idioms", "Pythonic code, Zen of Python, PEP 8", 1.0),
            SkillCapability("type_hints", "PEP 484 type hints, mypy, pydantic", 1.0),
            SkillCapability("async", "asyncio, async/await, aiohttp, anyio", 1.0),
            SkillCapability("testing", "pytest, unittest, mock, coverage", 1.0),
            SkillCapability("packaging", "setuptools, poetry, pip, pyproject.toml", 1.0),
            SkillCapability("performance", "Cython, numba, profiling, __slots__", 0.9),
        ]

    async def _execute_analyse(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(suggestions=["Add type hints", "Check async patterns", "Verify test coverage"])

    async def _execute_plan(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Python Execution Plan\n\n1. Define data models with dataclasses\n2. Add type hints everywhere\n3. Implement core logic with async support\n4. Add comprehensive pytest tests\n5. Configure pyproject.toml\n6. Set up pre-commit hooks (ruff, mypy)")

    async def _execute_review(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Python Code Review\n\n## Style\n- Follow PEP 8\n- Use f-strings over % or .format()\n- Prefer pathlib over os.path\n## Correctness\n- Type hints are correct\n- Context managers used where appropriate\n- No bare except clauses\n## Performance\n- List comprehensions over map/filter\n- Generators for large datasets\n- __slots__ for memory-sensitive classes")

    async def _execute_generate(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Generated by Python Expert\nfrom __future__ import annotations\n\nfrom dataclasses import dataclass\n\n\n@dataclass\nclass Item:\n    name: str\n    value: int\n\n    def display(self) -> str:\n        return f\"{self.name}: {self.value}\"")

    async def _execute_refactor(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Python Refactoring\n\n1. Replace dict with dataclass\n2. Add type hints\n3. Extract functions from large methods\n4. Use pathlib over os.path\n5. Replace mutable defaults with None\n6. Use enum for constants")

    async def _execute_debug(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Python Debug Analysis\n\n## Common Issues\n- Mutable default arguments\n- Late-binding closures\n- GIL contention\n- Circular imports\n- Module-level side effects\n## Tools\n- pdb/ipdb\n- pytest --pdb\n- cProfile\n- loguru")

    async def _execute_explain(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Python Explanation\n\nPython is a dynamically-typed, interpreted language emphasizing readability and productivity. Modern Python (3.10+) features pattern matching, type hints, and structural subtyping.")


class PythonExpert:
    Python = PythonExpertPack
