"""
Python Expert Skill Pack — domain expertise for Python programming language.
"""

from __future__ import annotations

import logging

from backend.modules.coding_agent.skills._types import (
    SkillCapability,
    SkillMetadata,
    SkillResult,
)
from backend.modules.coding_agent.skills.context._models import SkillContext
from backend.modules.coding_agent.skills.packs._base import BaseSkillPack

_LOG = logging.getLogger("naira.coding_agent.skills.packs.python")


class PythonExpertPack(BaseSkillPack):
    """Domain expert for Python programming language — idioms, patterns, typing, async, testing, packaging."""

    def __init__(self, *, logger: logging.Logger | None = None) -> None:
        super().__init__(
            logger=logger,
            metadata=SkillMetadata(
                name="Python Expert",
                description="Domain expert for Python — idioms, patterns, typing, async, testing, packaging",
                supported_languages=("python",),
                supported_frameworks=("django", "fastapi", "flask"),
                supported_file_extensions=(".py", ".pyi", ".pyx", ".pxd", ".pyw"),
                priority=90,
            ),
        )

    def _default_capabilities(self) -> list[SkillCapability]:
        return [
            SkillCapability("python_idioms", "Pythonic code, Zen of Python, PEP 8", 1.0),
            SkillCapability("type_hints", "PEP 484 type hints, mypy, pydantic", 1.0),
            SkillCapability("async", "asyncio, async/await, aiohttp, anyio", 1.0),
            SkillCapability("testing", "pytest, unittest, mock, coverage", 1.0),
            SkillCapability("packaging", "setuptools, poetry, pip, pyproject.toml", 1.0),
            SkillCapability("performance", "Cython, numba, profiling, __slots__", 0.9),
        ]

    async def _execute_analyse(self, context: SkillContext) -> SkillResult:
        content = f"Python Expert analysed {context.current_file.path if context.current_file else 'project'}"
        return SkillResult.ok(
            content=content,
            suggestions=["Add type hints", "Check async patterns", "Verify test coverage"],
        )

    async def _execute_plan(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(
            content=(
                "# Python Execution Plan\n\n"
                "1. Define data models with dataclasses / pydantic\n"
                "2. Add type hints everywhere\n"
                "3. Implement core logic with async support\n"
                "4. Add comprehensive pytest tests\n"
                "5. Configure pyproject.toml\n"
                "6. Set up code formatting and linting (ruff, mypy)"
            )
        )

    async def _execute_review(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(
            content=(
                "# Python Code Review\n\n"
                "## Style\n"
                "- Follow PEP 8 guidelines\n"
                "- Use f-strings over % or .format()\n"
                "- Prefer pathlib over os.path\n\n"
                "## Correctness\n"
                "- Verify type hint accuracy\n"
                "- Proper context manager usage\n"
                "- Avoid bare except clauses\n\n"
                "## Performance\n"
                "- List/dict comprehensions over map/filter\n"
                "- Use generators for large datasets\n"
                "- __slots__ for memory-sensitive data classes"
            )
        )

    async def _execute_generate(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(
            content=(
                "# Generated by Python Expert\n"
                "from __future__ import annotations\n\n"
                "from dataclasses import dataclass\n\n\n"
                "@dataclass\n"
                "class Item:\n"
                "    name: str\n"
                "    value: int\n\n"
                "    def display(self) -> str:\n"
                '        return f"{self.name}: {self.value}"\n'
            )
        )

    async def _execute_refactor(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(
            content=(
                "# Python Refactoring Suggestions\n\n"
                "1. Replace raw dictionaries with typed dataclasses or Pydantic models\n"
                "2. Add explicit type annotations to all function signatures\n"
                "3. Extract modular helper functions from monolithic methods\n"
                "4. Migrate legacy os.path operations to pathlib.Path\n"
                "5. Replace mutable default arguments with None\n"
                "6. Convert magic strings/numbers to Enum constants"
            )
        )

    async def _execute_debug(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(
            content=(
                "# Python Debug Analysis\n\n"
                "## Common Issue Checks\n"
                "- Mutable default arguments\n"
                "- Late-binding closures in loops\n"
                "- Thread safety & GIL contention\n"
                "- Circular imports\n"
                "- Module-level side effects\n\n"
                "## Diagnostic Tools\n"
                "- pdb / ipdb step debugger\n"
                "- pytest --pdb\n"
                "- cProfile & memory_profiler"
            )
        )

    async def _execute_explain(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(
            content=(
                "# Python Explanation\n\n"
                "Python is a high-level, dynamic programming language emphasizing code readability and developer productivity. "
                "Modern Python (3.10+) provides structural pattern matching, rich static typing annotations, native async/await concurrency, "
                "and an extensive ecosystem of high-performance libraries."
            )
        )


class PythonExpert:
    """Wrapper class providing namespace access to PythonExpertPack."""

    Python = PythonExpertPack
