from typing import Any
"""
React Expert Skill Pack — domain expertise for React.
"""

from __future__ import annotations

import logging

from backend.modules.coding_agent.skills._types import (
    SkillCapability,
    SkillMetadata,
    SkillResult,
)
from backend.modules.coding_agent.skills.context._models import SkillContext
from backend.modules.coding_agent.skills.packs._base import BaseSkillPack

_LOG = logging.getLogger("naira.coding_agent.skills.packs.react")


class ReactExpertPack(BaseSkillPack):
    def __init__(self, *, logger: logging.Logger | None = None) -> None:
        super().__init__(
            logger=logger,
            metadata=SkillMetadata(
                name="React Expert",
                description="Domain expert for React — hooks, state management, performance, testing",
                supported_languages=("javascript", "typescript"),
                supported_frameworks=("react",),
                supported_file_extensions=(".jsx", ".tsx"),
                priority=85,
            ),
        )

    def _default_capabilities(self) -> list[SkillCapability]:
        return [
            SkillCapability("hooks", "useState, useEffect, useuseReducer, custom hooks", 1.0),
            SkillCapability("state_management", "Any, Zustand, Redux Toolkit, Jotai, TanStack Query", 1.0),
            SkillCapability("performance", "React.memo, useMemo, useCallback, code splitting, Suspense", 1.0),
            SkillCapability("testing_react", "React Testing Library, Vitest, Cypress, Storybook", 0.9),
            SkillCapability("styling", "CSS Modules, Tailwind, styled-components, CSS-in-JS", 0.9),
        ]

    async def _execute_analyse(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(suggestions=["Check re-render performance", "Review hook dependencies", "Verify component composition"])

    async def _execute_plan(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# React Execution Plan\n\n1. Design component tree\n2. Plan state management strategy\n3. Implement with hooks\n4. Add error boundaries\n5. Optimize with React.lazy + Suspense\n6. Add unit tests (RTL)\n7. Add Storybook stories")

    async def _execute_review(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# React Code Review\n\n## Hooks\n- Proper dependency arrays\n- No hooks in conditions\n- Custom hooks for reusable logic\n## Performance\n- React.memo for expensive renders\n- useMemo for calculations\n- useCallback for stable references\n## Architecture\n- Container/presenter pattern\n- Lazy loading routes\n- Proper key props")

    async def _execute_generate(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="// Generated by React Expert\nimport { useState, useCallback } from 'react';\n\ninterface CounterProps {\n  initialValue?: number;\n}\n\nexport const Counter = ({ initialValue = 0 }: CounterProps) => {\n  const [count, setCount] = useState(initialValue);\n  const increment = useCallback(() => setCount(c => c + 1), []);\n  const decrement = useCallback(() => setCount(c => c - 1), []);\n  \n  return (\n    <div>\n      <button onClick={decrement}>-</button>\n      <span>{count}</span>\n      <button onClick={increment}>+</button>\n    </div>\n  );\n};")

    async def _execute_refactor(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# React Refactoring\n\n1. Extract custom hooks\n2. Split large components\n3. Add React.memo\n4. Replace class components with hooks\n5. Implement error boundaries\n6. Use Suspense for data fetching")

    async def _execute_debug(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# React Debug Analysis\n\n## Common Issues\n- Infinite re-render loops\n- Stale closures\n- Missing key props\n- Memory leaks in useEffect\n## Tools\n- React DevTools\n- React Profiler\n- Why Did You Render")

    async def _execute_explain(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# React Explanation\n\nReact is a declarative, component-based UI library. It uses a virtual DOM for efficient updates and hooks for stateful logic.")


class ReactExpert:
    React = ReactExpertPack
