"""
SQL Expert Skill Pack — domain expertise for SQL and relational databases.
"""

from __future__ import annotations

import logging

from backend.modules.coding_agent.skills._types import (
    SkillCapability,
    SkillMetadata,
    SkillResult,
)
from backend.modules.coding_agent.skills.context._models import SkillContext
from backend.modules.coding_agent.skills.packs._base import BaseSkillPack

_LOG = logging.getLogger("naira.coding_agent.skills.packs.sql")


class SQlExpertPack(BaseSkillPack):
    def __init__(self, *, logger: logging.Logger | None = None) -> None:
        super().__init__(
            logger=logger,
            metadata=SkillMetadata(
                name="SQL Expert",
                description="Domain expert for SQL — queries, optimization, schema design, migrations, ANSI SQL",
                supported_languages=("sql",),
                supported_frameworks=(),
                supported_file_extensions=(".sql", ".psql", ".mysql", ".sqlite"),
                priority=80,
            ),
        )

    def _default_capabilities(self) -> list[SkillCapability]:
        return [
            SkillCapability("query_optimization", "EXPLAIN, index usage, query planning, JOIN optimization", 1.0),
            SkillCapability("schema_design", "Normalization, denormalization, constraints, foreign keys", 1.0),
            SkillCapability("migrations", "Schema migrations, versioning, rollback strategies", 1.0),
            SkillCapability("window_functions", "ROW_NUMBER, RANK, LAG/LEAD, PARTITION BY", 1.0),
            SkillCapability("cte", "Common Table Expressions, recursive CTEs", 1.0),
            SkillCapability("transactions", "ACID, isolation levels, locking, deadlock prevention", 1.0),
        ]

    async def _execute_analyse(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(suggestions=["Check query execution plan", "Review index coverage", "Verify join performance"])

    async def _execute_plan(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# SQL Execution Plan\n\n1. Design schema with proper normalization\n2. Create indexes based on query patterns\n3. Write optimized queries with EXPLAIN\n4. Add constraints for data integrity\n5. Create migration scripts\n6. Set up query monitoring")

    async def _execute_review(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# SQL Code Review\n\n## Queries\n- Use EXPLAIN ANALYZE\n- Avoid SELECT *\n- Proper JOIN conditions\n- Index usage verified\n## Schema\n- Appropriate data types\n- NOT NULL where applicable\n- Foreign key constraints\n- Index naming convention\n## Performance\n- Covering indexes\n- Partial indexes\n- Materialized views\n- Partitioning for large tables")

    async def _execute_generate(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="-- Generated by SQL Expert\nCREATE TABLE users (\n    id BIGSERIAL PRIMARY KEY,\n    email VARCHAR(255) NOT NULL UNIQUE,\n    name VARCHAR(100) NOT NULL,\n    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),\n    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()\n);\n\nCREATE INDEX idx_users_email ON users (email);\nCREATE INDEX idx_users_created_at ON users (created_at DESC);")

    async def _execute_refactor(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# SQL Refactoring\n\n1. Add missing indexes\n2. Optimize slow queries\n3. Normalize repeating groups\n4. Add foreign key constraints\n5. Partition large tables\n6. Use CTEs for readability")

    async def _execute_debug(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# SQL Debug Analysis\n\n## Common Issues\n- Missing indexes causing full scans\n- N+1 queries\n- Deadlocks\n- Implicit type conversions\n- Lock contention\n## Tools\n- EXPLAIN ANALYZE\n- pg_stat_statements\n- pgBadger\n- slow_query_log")

    async def _execute_explain(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# SQL Explanation\n\nSQL is the standard language for relational database management, supporting data querying, manipulation, schema definition, and transaction control.")


class SQlExpert:
    SQL = SQlExpertPack
