"""
TypeScript Expert Skill Pack — domain expertise for TypeScript.
"""

from __future__ import annotations

import logging

from backend.modules.coding_agent.skills._types import (
    SkillCapability,
    SkillMetadata,
    SkillResult,
)
from backend.modules.coding_agent.skills.context._models import SkillContext
from backend.modules.coding_agent.skills.packs._base import BaseSkillPack

_LOG = logging.getLogger("naira.coding_agent.skills.packs.typescript")


class TypeScriptExpertPack(BaseSkillPack):
    def __init__(self, *, logger: logging.Logger | None = None) -> None:
        super().__init__(
            logger=logger,
            metadata=SkillMetadata(
                name="TypeScript Expert",
                description="Domain expert for TypeScript — advanced types, generics, tsconfig, type safety",
                supported_languages=("typescript",),
                supported_frameworks=("react", "nextjs", "angular", "nestjs"),
                supported_file_extensions=(".ts", ".tsx", ".mts", ".cts"),
                priority=85,
            ),
        )

    def _default_capabilities(self) -> list[SkillCapability]:
        return [
            SkillCapability("advanced_types", "Conditional types, mapped types, template literal types, infer", 1.0),
            SkillCapability("generics", "Generic constraints, variadic tuples, branded types", 1.0),
            SkillCapability("tsconfig", "Compiler options, strict mode, paths, project references", 1.0),
            SkillCapability("type_safety", "Branded types, nominal typing, type guards, assertion functions", 1.0),
            SkillCapability("decorators", "Experimental and stage 3 decorators", 0.9),
        ]

    async def _execute_analyse(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(suggestions=["Enable strict mode", "Review type exports", "Add branded types for safety"])

    async def _execute_plan(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# TypeScript Execution Plan\n\n1. Define interfaces and types\n2. Enable strict mode\n3. Use discriminated unions\n4. Add generic utility types\n5. Configure paths in tsconfig\n6. Add type tests with expect-type")

    async def _execute_review(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# TypeScript Code Review\n\n## Type Safety\n- strict mode enabled\n- No implicit any\n- Proper discriminated unions\n- Exhaustive checks with never\n## Generics\n- Proper constraints\n- Avoid over-generalization\n- Use satisfies operator\n## Config\n- target ES2022+\n- module NodeNext\n- declaration: true")

    async def _execute_generate(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="// Generated by TypeScript Expert\ntype Result<T, E = Error> = \n  | { success: true; value: T }\n  | { success: false; error: E };\n\nconst divide = (a: number, b: number): Result<number> => {\n  if (b === 0) return { success: false, error: new Error('Division by zero') };\n  return { success: true, value: a / b };\n};")

    async def _execute_refactor(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# TypeScript Refactoring\n\n1. Replace enums with const objects + union types\n2. Add satisfies where appropriate\n3. Use branded types for IDs\n4. Extract shared types\n5. Add type predicates\n6. Use template literal types")

    async def _execute_debug(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# TypeScript Debug Analysis\n\n## Common Issues\n- Type narrowing failures\n- Complex generic inference\n- Module resolution errors\n- Decorator metadata\n## Tools\n- tsc --noEmit\n- ts-error-translator\n- TypeScript playground")

    async def _execute_explain(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# TypeScript Explanation\n\nTypeScript is a typed superset of JavaScript that compiles to plain JS. It adds static typing, interfaces, generics, and advanced type system features.")


class TypeScriptExpert:
    TS = TypeScriptExpertPack
