"""
Web Security Expert Skill Pack — domain expertise for web application security.
"""

from __future__ import annotations

import logging

from backend.modules.coding_agent.skills._types import (
    SkillCapability,
    SkillMetadata,
    SkillResult,
)
from backend.modules.coding_agent.skills.context._models import SkillContext
from backend.modules.coding_agent.skills.packs._base import BaseSkillPack

_LOG = logging.getLogger("naira.coding_agent.skills.packs.web_security")


class WebSecurityExpertPack(BaseSkillPack):
    def __init__(self, *, logger: logging.Logger | None = None) -> None:
        super().__init__(
            logger=logger,
            metadata=SkillMetadata(
                name="Web Security Expert",
                description="Domain expert for web security — OWASP Top 10, authentication, authorization, XSS, CSRF, SQLi, CSP",
                supported_languages=(),
                supported_frameworks=(),
                supported_file_extensions=(),
                priority=50,
            ),
        )

    def _default_capabilities(self) -> list[SkillCapability]:
        return [
            SkillCapability("owasp_top10", "OWASP Top 10 vulnerabilities and mitigation strategies", 1.0),
            SkillCapability("authentication", "OAuth 2.0, OpenID Connect, JWT, session management, MFA", 1.0),
            SkillCapability("xss_csrf", "XSS (reflected, stored, DOM), CSRF, CORS, CSP", 1.0),
            SkillCapability("injection", "SQL injection, NoSQL injection, command injection, LDAP injection", 1.0),
            SkillCapability("security_headers", "CSP, HSTS, X-Frame-Options, X-Content-Type-Options, Referrer-Policy", 1.0),
            SkillCapability("crypto", "Hashing, encryption, TLS, key management, password hashing (bcrypt, argon2)", 1.0),
        ]

    async def _execute_analyse(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(suggestions=["Review authentication flow", "Check for injection vulnerabilities", "Verify security headers"])

    async def _execute_plan(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Web Security Execution Plan\n\n1. Implement proper authentication (OAuth 2.0)\n2. Add authorization (RBAC/ABAC)\n3. Set security headers (CSP, HSTS)\n4. Implement input validation and sanitization\n5. Use parameterized queries (prevent SQLi)\n6. Add CSRF tokens\n7. Set up rate limiting\n8. Implement audit logging")

    async def _execute_review(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Web Security Code Review\n\n## Authentication\n- Password hashing (bcrypt/argon2)\n- Session management secure\n- MFA implemented\n- Account lockout after failures\n## Authorization\n- RBAC properly enforced\n- Least privilege principle\n- Server-side authorization checks\n## OWASP Top 10\n- No SQL injection (parameterized queries)\n- XSS prevented (output encoding)\n- CSRF tokens present\n- Insecure deserialization checked\n## Headers\n- Content-Security-Policy\n- Strict-Transport-Security\n- X-Frame-Options: DENY\n- X-Content-Type-Options: nosniff")

    async def _execute_generate(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Generated by Web Security Expert\nclass SecurityHeaders:\n    CSP = \"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'\"\n    HSTS = \"max-age=31536000; includeSubDomains\"\n    XFO = \"DENY\"\n    XCTO = \"nosniff\"\n    RP = \"strict-origin-when-cross-origin\"\n\ndef add_security_headers(response):\n    response.headers['Content-Security-Policy'] = SecurityHeaders.CSP\n    response.headers['Strict-Transport-Security'] = SecurityHeaders.HSTS\n    response.headers['X-Frame-Options'] = SecurityHeaders.XFO\n    response.headers['X-Content-Type-Options'] = SecurityHeaders.XCTO\n    response.headers['Referrer-Policy'] = SecurityHeaders.RP\n    return response")

    async def _execute_refactor(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Web Security Refactoring\n\n1. Replace raw SQL with ORM/parameterized queries\n2. Add CSP headers\n3. Implement rate limiting\n4. Add request validation middleware\n5. Replace weak hash algorithms\n6. Add audit logging")

    async def _execute_debug(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Web Security Debug Analysis\n\n## Common Issues\n- CORS misconfiguration\n- Missing security headers\n- Weak password policies\n- Session fixation\n## Tools\n- OWASP ZAP\n- Burp Suite\n- Semgrep\n- SonarQube\n- Snyk")

    async def _execute_explain(self, context: SkillContext) -> SkillResult:
        return SkillResult.ok(content="# Web Security Explanation\n\nWeb security encompasses practices to protect web applications from attacks including XSS, SQL injection, CSRF, and authentication bypasses, guided by the OWASP Top 10.")


class WebSecurityExpert:
    WebSecurity = WebSecurityExpertPack
