"""
Built-in Skills — Default executable intelligence skills for Naira OS.
"""

from __future__ import annotations

import logging
from typing import List

from backend.modules.skills.models import Skill, SkillCategory

_LOG = logging.getLogger("naira.skills.builtin")


def get_builtin_skills() -> List[Skill]:
    """Factory returning default standard built-in skills."""
    return [
        Skill(
            id="skill.web.open_website",
            name="Open Website",
            description="Navigates to a target URL or opens web pages in browser.",
            category=SkillCategory.WEB,
            required_capabilities=["browser.installed", "network.available"],
            optional_capabilities=["playwright.available"],
            supported_platforms=["*"],
            required_permissions=["network"],
            complexity_score=0.2,
            estimated_duration=3.0,
            executor="browser.navigate",
            verifier="browser.verify_loaded",
            rollback_support=False,
            tags=["web", "browse", "navigate", "url", "open_page", "visit_site"],
            aliases=["browse_url", "visit_site", "open_page", "browse"],
            version="1.0.0",
        ),
        Skill(
            id="skill.web.search_web",
            name="Search Web",
            description="Performs web search queries and returns summarized information.",
            category=SkillCategory.WEB,
            required_capabilities=["network.available"],
            optional_capabilities=["browser.installed"],
            supported_platforms=["*"],
            required_permissions=["network"],
            complexity_score=0.3,
            estimated_duration=4.0,
            executor="search.execute_query",
            verifier=None,
            rollback_support=False,
            tags=["search", "web", "google", "query", "research", "find"],
            aliases=["web_search", "google_search", "lookup_online"],
            version="1.0.0",
        ),
        Skill(
            id="skill.coding.code_review",
            name="Code Review",
            description="Performs automated code quality, linting, and architectural review.",
            category=SkillCategory.CODING,
            required_capabilities=["python.installed"],
            optional_capabilities=["git.installed"],
            supported_platforms=["*"],
            required_permissions=["file_system"],
            complexity_score=0.6,
            estimated_duration=10.0,
            executor="coding.review_code",
            verifier="coding.verify_diff",
            rollback_support=True,
            tags=["code", "review", "lint", "quality", "audit", "refactor"],
            aliases=["review_code", "code_audit", "lint_code"],
            version="1.0.0",
        ),
        Skill(
            id="skill.vcs.git_ops",
            name="Git Operations",
            description="Executes repository status, commits, branching, and pull requests.",
            category=SkillCategory.VCS,
            required_capabilities=["git.installed"],
            optional_capabilities=["network.available"],
            supported_platforms=["*"],
            required_permissions=["file_system", "process_execute"],
            complexity_score=0.4,
            estimated_duration=5.0,
            executor="vcs.git_execute",
            verifier="vcs.git_verify",
            rollback_support=True,
            tags=["git", "vcs", "commit", "branch", "checkout", "pull", "push"],
            aliases=["git_command", "repo_version_control"],
            version="1.0.0",
        ),
        Skill(
            id="skill.mobile.android_flashing",
            name="Android Flashing",
            description="Flashes ROMs, firmware, or APK packages to connected Android ADB devices.",
            category=SkillCategory.MOBILE,
            required_capabilities=["adb.installed"],
            optional_capabilities=["fastboot.installed"],
            supported_platforms=["windows", "linux", "darwin"],
            required_permissions=["process_execute", "usb"],
            complexity_score=0.8,
            estimated_duration=60.0,
            executor="mobile.android_flash",
            verifier="mobile.verify_boot",
            rollback_support=True,
            tags=["android", "adb", "flash", "firmware", "rom", "apk"],
            aliases=["flash_android", "adb_flash", "install_rom"],
            version="1.0.0",
        ),
        Skill(
            id="skill.coding.repository_analysis",
            name="Repository Analysis",
            description="Analyzes codebase structure, files, dependencies, and imports.",
            category=SkillCategory.CODING,
            required_capabilities=[],
            optional_capabilities=["git.installed", "python.installed"],
            supported_platforms=["*"],
            required_permissions=["file_system"],
            complexity_score=0.5,
            estimated_duration=8.0,
            executor="coding.analyze_repo",
            verifier=None,
            rollback_support=False,
            tags=["repo", "repository", "analysis", "codebase", "structure", "inspect"],
            aliases=["analyze_repo", "codebase_analysis", "scan_repo"],
            version="1.0.0",
        ),
        Skill(
            id="skill.devops.project_build",
            name="Project Build",
            description="Compiles, builds, and packages application artifacts.",
            category=SkillCategory.DEVOPS,
            required_capabilities=[],
            optional_capabilities=["docker.installed"],
            supported_platforms=["*"],
            required_permissions=["file_system", "process_execute"],
            complexity_score=0.5,
            estimated_duration=20.0,
            executor="devops.build_project",
            verifier="devops.verify_artifact",
            rollback_support=True,
            tags=["build", "compile", "package", "docker", "maven", "npm_build"],
            aliases=["build_app", "compile_code", "make_build"],
            version="1.0.0",
        ),
        Skill(
            id="skill.document.pdf_analysis",
            name="PDF Analysis",
            description="Parses, extracts text, tables, and summarizes PDF document contents.",
            category=SkillCategory.DOCUMENT,
            required_capabilities=["python.installed"],
            optional_capabilities=[],
            supported_platforms=["*"],
            required_permissions=["file_system"],
            complexity_score=0.4,
            estimated_duration=5.0,
            executor="document.analyze_pdf",
            verifier=None,
            rollback_support=False,
            tags=["pdf", "document", "parse", "extract", "ocr", "summarize"],
            aliases=["parse_pdf", "read_pdf", "pdf_summary"],
            version="1.0.0",
        ),
        Skill(
            id="skill.system.system_diagnostics",
            name="System Diagnostics",
            description="Monitors local machine CPU, RAM, disk, processes, and thermal metrics.",
            category=SkillCategory.SYSTEM,
            required_capabilities=[],
            optional_capabilities=["psutil.available", "gpu.available"],
            supported_platforms=["*"],
            required_permissions=["system_info"],
            complexity_score=0.2,
            estimated_duration=2.0,
            executor="system.run_diagnostics",
            verifier=None,
            rollback_support=False,
            tags=["system", "diagnostics", "health", "cpu", "memory", "stats"],
            aliases=["health_check", "check_system", "hardware_info"],
            version="1.0.0",
        ),
        Skill(
            id="skill.system.software_installation",
            name="Software Installation",
            description="Installs or updates software packages using system package managers.",
            category=SkillCategory.SYSTEM,
            required_capabilities=["network.available"],
            optional_capabilities=["winget.installed", "apt.installed"],
            supported_platforms=["*"],
            required_permissions=["process_execute", "admin"],
            complexity_score=0.6,
            estimated_duration=45.0,
            executor="system.install_software",
            verifier="system.verify_installation",
            rollback_support=True,
            tags=["install", "software", "package", "winget", "apt", "pip"],
            aliases=["install_package", "setup_software", "download_app"],
            version="1.0.0",
        ),
    ]
