name: Android Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Inject google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > naira_android_app/app/google-services.json

      - name: Build Debug APK
        run: gradle assembleDebug
        working-directory: ./naira_android_app

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Naira-Remote-Bridge-APK
          path: naira_android_app/app/build/outputs/apk/debug/app-debug.apk
